//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategorije
    {
        public kategorije()
        {
            this.biografije = new HashSet<biografije>();
            this.oglasi = new HashSet<oglasi>();
        }
    
        public int idkategorije { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<biografije> biografije { get; set; }
        public virtual ICollection<oglasi> oglasi { get; set; }
    }
}
