//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class korisnici
    {
        public korisnici()
        {
            this.poslodavci = new HashSet<poslodavci>();
            this.posloprimci = new HashSet<posloprimci>();
        }
    
        public int idkorisnici { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string tip_korisnika { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public string GUID { get; set; }
    
        public virtual ICollection<poslodavci> poslodavci { get; set; }
        public virtual ICollection<posloprimci> posloprimci { get; set; }
    }
}
