//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokacije
    {
        public lokacije()
        {
            this.poslodavci = new HashSet<poslodavci>();
            this.posloprimci = new HashSet<posloprimci>();
        }
    
        public int idlokacije { get; set; }
        public string drzava { get; set; }
        public string kanton { get; set; }
        public string grad { get; set; }
        public string postanski_broj { get; set; }
    
        public virtual ICollection<poslodavci> poslodavci { get; set; }
        public virtual ICollection<posloprimci> posloprimci { get; set; }
    }
}
