//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oglasi
    {
        public int idoglasi { get; set; }
        public int idposlodavci { get; set; }
        public string naziv_pozicije { get; set; }
        public Nullable<System.DateTime> datum_objave { get; set; }
        public Nullable<System.DateTime> datum_zavrsetka { get; set; }
        public string text_oglasa { get; set; }
        public Nullable<int> broj_pozicija { get; set; }
        public string spol { get; set; }
        public string kontakt_email { get; set; }
        public Nullable<int> idkategorije { get; set; }
        public string tip_oglasa { get; set; }
    
        public virtual kategorije kategorije { get; set; }
    }
}
