//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posloprimci
    {
        public posloprimci()
        {
            this.biografije = new HashSet<biografije>();
        }
    
        public int idposloprimci { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public string spol { get; set; }
        public string strucna_sprema { get; set; }
        public string telefon { get; set; }
        public Nullable<int> idlokacija { get; set; }
        public Nullable<int> idkorisnici { get; set; }
    
        public virtual ICollection<biografije> biografije { get; set; }
        public virtual korisnici korisnici { get; set; }
        public virtual lokacije lokacije { get; set; }
    }
}
