//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poslodavci
    {
        public int idposlodavci { get; set; }
        public Nullable<int> idkorisnici { get; set; }
        public string vrsta { get; set; }
        public string djelatnost { get; set; }
        public string naziv { get; set; }
        public string OIB { get; set; }
        public int idlokacije { get; set; }
        public string opis { get; set; }
        public string telefon { get; set; }
        public string webpage { get; set; }
        public Nullable<int> broj_zaposlenih { get; set; }
        public string tip_poslodavca { get; set; }
    
        public virtual korisnici korisnici { get; set; }
        public virtual lokacije lokacije { get; set; }
    }
}
